AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys a Secret Manager for the db-tier

Parameters:
  AppName:
    Type: String
    Default: shopify
  dbname:
    Type: String
    Default: shopify_api
  username:
    Type: String
    Default: apiuser

Resources:
  DbSecrets:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      Description: Contains the secrets for the database tier
      GenerateSecretString:
        SecretStringTemplate:
          Fn::Sub: '{"dbname": "${dbname}",
          "username": "${username}"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

Outputs:
  DbSecrets:
    Description: "Secrets for the db-tier."
    Value:
      Ref: "DbSecrets"
    Export:
      Name: !Sub "${AWS::Region}-${AppName}:db-secrets"
