AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys a Secret Manager for the web-tier, and a VPC enpoint for both Secret Managers

Parameters:
  AppName:
    Type: String
    Default: shopify
  NodeEnvironment:
    Type: String
    Default: development
  AWSEnvironment:
    Type: String
    Default: staging
  AppDomain:
    Type: String
    Description: The final URL of our application
  ShopifyAPIKey:
    Type: String
    Description: Taken from Shopify App Partner dashboard - Update this later in Secret Manager directly
    Default: dummy
  ShopifyAPISsecret:
    Type: String
    Description: Taken from Shopify App Partner dashboard  - Update this later in Secret Manager directly
    Default: dummy
  ShopifyScopes:
    Type: String
    Default: "read_themes, write_products"
  CognitoUsername:
    Type: String
    Description: Created in Cognito - Update this later is Secret Manager directly
    Default: dummy
  CognitoPassword:
    Type: String
    Description: Created in Cognito - Update this later is Secret Manager directly
    Default: dummy

Resources:
  WebSecrets:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      Description: Contains the secrets for the web tier
      SecretString: !Join
        - ""
        - - '{"NODE_ENV": "'
          - !Ref NodeEnvironment
          - '","SHOPIFY_ENV": "'
          - !Ref AWSEnvironment
          - '","SHOPIFY_API_URL": "'
          - !Join
            - ""
            - - Fn::ImportValue:
                  Fn::Sub: "${AWS::Region}-${AppName}:api-gateway-endpoint"
              - "/"
              - !Ref NodeEnvironment
          - '","DYNAMODB_URL": "'
          - Fn::Sub: "https://dynamodb.${AWS::Region}.amazonaws.com"
          - '","SHOPIFY_API_KEY": "'
          - !Ref ShopifyAPIKey
          - '","SHOPIFY_API_SECRET": "'
          - !Ref ShopifyAPISsecret
          - '","SCOPES": "'
          - !Ref ShopifyScopes
          - '","HOST": "'
          - !Ref AppDomain
          - '","COGNITO_USERPOOL_ID": "'
          - Fn::ImportValue:
              Fn::Sub: "${AWS::Region}-${AppName}:cognito-userpool-id"
          - '","COGNITO_USERPOOL_CLIENT_ID": "'
          - Fn::ImportValue:
              Fn::Sub: "${AWS::Region}-${AppName}:cognito-userpool-client-id"
          - '","COGNITO_USERNAME": "'
          - !Ref CognitoUsername
          - '","COGNITO_PASSWORD": "'
          - !Ref CognitoPassword
          - '"}'

Outputs:
  DbSecrets:
    Description: Secrets for the app-tier
    Value:
      Ref: "WebSecrets"
    Export:
      Name: !Sub "${AWS::Region}-${AppName}:web-secrets"
